version: '3'
services:
    db:
        build: ./db
        ports:
        - "3307:3306"
    api:
        build: ./api
        depends_on:
          - db
        ports:
        - "8080:8080"
    front:
        build: ./front
        depends_on:
          - api
        ports:
        - "80:80"